// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  request

import (
  "github.com/mailru/easyjson/jlexer"
  "github.com/mailru/easyjson/jwriter"
)

func ( CaptchaDto ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CaptchaDto ) UnmarshalJSON([]byte) error { return nil }
func ( CaptchaDto ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CaptchaDto ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CaptchaDto *CaptchaDto

func ( LoginParamsDto ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LoginParamsDto ) UnmarshalJSON([]byte) error { return nil }
func ( LoginParamsDto ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LoginParamsDto ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LoginParamsDto *LoginParamsDto

func ( XsrfDto ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* XsrfDto ) UnmarshalJSON([]byte) error { return nil }
func ( XsrfDto ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* XsrfDto ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_XsrfDto *XsrfDto
