// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jlexer"
  "github.com/mailru/easyjson/jwriter"
)

func ( BaseWrapper ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BaseWrapper ) UnmarshalJSON([]byte) error { return nil }
func ( BaseWrapper ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BaseWrapper ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BaseWrapper *BaseWrapper
